const img1 =
	'https://t4.ftcdn.net/jpg/03/69/19/81/360_F_369198116_K0sFy2gRTo1lmIf5jVGeQmaIEibjC3NN.jpg';
const img2 =
	'https://t3.ftcdn.net/jpg/02/65/60/80/360_F_265608067_Nth2hs7Ri68NZBgHHhGuWIxaP6Z1m170.jpg';
const img3 =
	'https://t3.ftcdn.net/jpg/06/33/80/44/360_F_633804450_DWH5bj77LdDwlCSvMcqy6qVk4j9kchT3.jpg';
const img4 =
	'https://cewd.vtc.edu/wp-content/uploads/2022/02/GES3044_Web-Development-Bootcamp_Self-Paced-with-Coaching.jpg';
const img5 =
	'https://c8.alamy.com/comp/P9YRGJ/positive-web-developer-using-a-smartphone-while-working-with-holograms-P9YRGJ.jpg';

export const auditLogs = [
	{
		id: 1,
		user: 'admin',
		email: 'admin@example.com',
		action: 'Created new course',
		course: 'Course: "Introduction to Programming"',
		image: img1,
		createdAt: '2024-02-01',
		updatedAt: '2024-02-10',
		status: true,
	},
	{
		id: 2,
		user: 'instructor',
		email: 'instructor@example.com',
		action: 'Updated course description',
		course: 'Course: "Introduction to Web Development"',
		image: img2,
		createdAt: '2023-12-15',
		updatedAt: '2024-01-20',
		status: true,
	},
	{
		id: 3,
		user: 'student',
		email: 'student@example.com',
		action: 'Submitted assignment',
		course: 'Assignment: "HTML Basics"',
		image: img3,
		createdAt: '2024-01-10',
		updatedAt: '2024-03-05',
		status: true,
	},
	{
		id: 4,
		user: 'admin',
		email: 'admin@example.com',
		action: 'Deleted user account',
		course: 'User: "john_doe"',
		image: img4,
		createdAt: '2024-03-01',
		updatedAt: '2024-03-01',
		status: true,
	},
	{
		id: 5,
		user: 'instructor',
		email: 'instructor2@example.com',
		action: 'Created new quiz',
		course: 'Quiz: "JavaScript Basics"',
		image: img5,
		createdAt: '2024-02-20',
		updatedAt: '2024-02-25',
		status: true,
	},
	{
		id: 6,
		user: 'student',
		email: 'student2@example.com',
		action: 'Joined new course',
		course: 'Course: "React for Beginners"',
		image: img1,
		createdAt: '2024-01-15',
		updatedAt: '2024-01-15',
		status: true,
	},
	{
		id: 7,
		user: 'admin',
		email: 'admin@example.com',
		action: 'Updated system settings',
		course: 'Settings: "Email Notifications"',
		image: img2,
		createdAt: '2024-02-28',
		updatedAt: '2024-02-28',
		status: true,
	},
	{
		id: 8,
		user: 'instructor',
		email: 'instructor3@example.com',
		action: 'Graded assignment',
		course: 'Assignment: "CSS Flexbox"',
		image: img3,
		createdAt: '2024-01-25',
		updatedAt: '2024-01-30',
		status: true,
	},
	{
		id: 9,
		user: 'student',
		email: 'student3@example.com',
		action: 'Completed course',
		course: 'Course: "Advanced Node.js"',
		image: img4,
		createdAt: '2024-02-10',
		updatedAt: '2024-02-10',
		status: true,
	},
	{
		id: 10,
		user: 'admin',
		email: 'admin@example.com',
		action: 'Revoked user access',
		course: 'User: "jane_doe"',
		image: img5,
		createdAt: '2024-03-05',
		updatedAt: '2024-03-05',
		status: true,
	},
	{
		id: 11,
		user: 'instructor',
		email: 'instructor4@example.com',
		action: 'Published new course',
		course: 'Course: "Introduction to Docker"',
		image: img1,
		createdAt: '2024-03-01',
		updatedAt: '2024-03-03',
		status: true,
	},
	{
		id: 12,
		user: 'student',
		email: 'student4@example.com',
		action: 'Asked a question in forum',
		course: 'Course: "Data Structures"',
		image: img2,
		createdAt: '2024-02-20',
		updatedAt: '2024-02-20',
		status: true,
	},
];
