const img1 =
	'https://t4.ftcdn.net/jpg/03/69/19/81/360_F_369198116_K0sFy2gRTo1lmIf5jVGeQmaIEibjC3NN.jpg';
const img2 =
	'https://t3.ftcdn.net/jpg/02/65/60/80/360_F_265608067_Nth2hs7Ri68NZBgHHhGuWIxaP6Z1m170.jpg';
const img3 =
	'https://t3.ftcdn.net/jpg/06/33/80/44/360_F_633804450_DWH5bj77LdDwlCSvMcqy6qVk4j9kchT3.jpg';
const img4 =
	'https://cewd.vtc.edu/wp-content/uploads/2022/02/GES3044_Web-Development-Bootcamp_Self-Paced-with-Coaching.jpg';
const img5 =
	'https://c8.alamy.com/comp/P9YRGJ/positive-web-developer-using-a-smartphone-while-working-with-holograms-P9YRGJ.jpg';

export const adminUser = [
	{
		id: 1,
		name: 'Emma Smith',
		thumb: img2,
		adminBelongsTo: 'Web Development',
		description: 'An introduction to network security concepts, protocols, and best practices.',
		email: 'emma@example.com',
		contactNumber: '987-654-3210',
		address: '456 Elm Avenue, Town, Country',
		createdAt: '2024-02-01',
		updatedAt: '2024-02-10',
		status: 'Active',
	},
	{
		id: 2,
		name: 'John Doe',
		thumb: img1,
		adminBelongsTo: 'Software Engineering',
		description: 'Expert in full-stack development and agile methodologies.',
		email: 'john@example.com',
		contactNumber: '123-456-7890',
		address: '123 Oak Street, City, Country',
		createdAt: '2023-12-15',
		updatedAt: '2024-01-20',
		status: 'Active',
	},
	{
		id: 3,
		name: 'Ava Johnson',
		thumb: img3,
		adminBelongsTo: 'Data Science',
		description: 'Specializes in machine learning and data visualization techniques.',
		email: 'ava@example.com',
		contactNumber: '456-789-0123',
		address: '789 Maple Lane, Suburb, Country',
		createdAt: '2024-01-10',
		updatedAt: '2024-03-05',
		status: 'Inactive',
	},
	{
		id: 4,
		name: 'Liam Brown',
		thumb: img4,
		adminBelongsTo: 'Cybersecurity',
		description: 'Focuses on ethical hacking and penetration testing.',
		email: 'liam@example.com',
		contactNumber: '321-654-9870',
		address: '321 Pine Road, Village, Country',
		createdAt: '2023-11-05',
		updatedAt: '2024-01-25',
		status: 'Active',
	},
	{
		id: 5,
		name: 'Sophia Davis',
		thumb: img5,
		adminBelongsTo: 'Mobile Development',
		description: 'Experienced in iOS and Android app development.',
		email: 'sophia@example.com',
		contactNumber: '654-321-0987',
		address: '654 Birch Avenue, Metropolis, Country',
		createdAt: '2024-02-20',
		updatedAt: '2024-03-10',
		status: 'Restricted',
	},
	{
		id: 6,
		name: 'James Wilson',
		thumb: img2,
		adminBelongsTo: 'Cloud Computing',
		description: 'Cloud architect with expertise in AWS and Azure platforms.',
		email: 'james@example.com',
		contactNumber: '789-012-3456',
		address: '789 Cedar Street, Hamlet, Country',
		createdAt: '2023-10-01',
		updatedAt: '2024-01-15',
		status: 'Inactive',
	},
	{
		id: 7,
		name: 'Isabella Martinez',
		thumb: img3,
		adminBelongsTo: 'DevOps',
		description: 'Proficient in continuous integration and continuous deployment.',
		email: 'isabella@example.com',
		contactNumber: '890-123-4567',
		address: '890 Spruce Drive, Borough, Country',
		createdAt: '2024-01-05',
		updatedAt: '2024-02-28',
		status: 'Active',
	},
	{
		id: 8,
		name: 'William Anderson',
		thumb: img4,
		adminBelongsTo: 'AI Research',
		description: 'AI researcher with a focus on natural language processing.',
		email: 'william@example.com',
		contactNumber: '901-234-5678',
		address: '901 Willow Lane, Township, Country',
		createdAt: '2023-09-20',
		updatedAt: '2024-01-30',
		status: 'Active',
	},
	{
		id: 9,
		name: 'Mia Taylor',
		thumb: img5,
		adminBelongsTo: 'UI/UX Design',
		description: 'Creative UI/UX designer with a passion for user-centered design.',
		email: 'mia@example.com',
		contactNumber: '012-345-6789',
		address: '012 Aspen Road, District, Country',
		createdAt: '2024-02-15',
		updatedAt: '2024-03-15',
		status: 'Inactive',
	},
	{
		id: 10,
		name: 'Ethan Thomas',
		thumb: img1,
		adminBelongsTo: 'Project Management',
		description: 'Certified project manager with experience in large-scale IT projects.',
		email: 'ethan@example.com',
		contactNumber: '123-789-4560',
		address: '123 Redwood Street, Region, Country',
		createdAt: '2023-11-10',
		updatedAt: '2024-02-20',
		status: 'Active',
	},
];
